steps:
- name: node:14
  entrypoint: yarn
  args: ["install"]
- name: node:14
  entrypoint: yarn
  args: ["build"]
- name: node:14
  entrypoint: yarn
  args: ["create-env"]
  env:
    - 'SECRET=${_SECRET}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"