name: 'Deploy App'

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: ../../app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
