name: 'Verify PR'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  acceptance:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build app
      run: yarn build
    - name: Acceptance tests
      run: |
          yarn start &
          yarn acceptance
  coverage:
    runs-on: ubuntu-latest
    env:
        CI_JOB_NUMBER: 1
    steps:
        - uses: actions/checkout@v1
        - uses: artiomtr/jest-coverage-report-action@v1.2
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              threshold: 100
